version: '3.8'

services:
  file-upload-app:
    build:
      context: ./file-upload-app
    ports:
        - "5001:5001"
    user: root

  health-check:
    build:
      context: ./HealthCheck
      dockerfile: Dockerfile-HealthCheck
    ports:
        - "5005:80"
    user: root
    environment:
      - FLASK_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /etc/TLMRIS/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - file-upload-app
      - health-check
