# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements.txt file into the container at /usr/src/app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's source code from your host to your filesystem.
COPY . .

# Make port 80 available to the world outside this container
EXPOSE 80

# Run the script when the container launches
CMD ["python", "r6-dissect-runner.py"]
