# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir watchdog flask boto3 

# Copy the rest of your application's source code from your host to your filesystem.
COPY dissect-runner/r6-dissect-runner.py /usr/src/app
COPY dissect-runner/r6-dissect /usr/src/app

# Expose port 5000 for the Flask app
EXPOSE 5000

# Run the script when the container launches
CMD ["python", "r6-dissect-runner.py"]
