# Use the official Node.js 14 image.
FROM node:14

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy local code to the container image.
COPY . .

# Build the app for production.
RUN npm run build

# Use a base image for serving the build files.
FROM nginx:alpine
COPY --from=0 /usr/src/app/build /usr/share/nginx/html

# Expose port 5001 to the outside world
EXPOSE 5001

# Update the default Nginx configuration file to listen on port 5001
RUN sed -i 's/listen       80;/listen       5001;/' /etc/nginx/conf.d/default.conf

# Start the server.
CMD ["nginx", "-g", "daemon off;"]
