FROM node:14

# Install Python and pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Install AWS CLI
RUN pip3 install awscli

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY file-upload-app/package*.json ./

RUN npm install

# Bundle app source
COPY file-upload-app/ .

EXPOSE 5001

CMD [ "npm", "start" ]
