FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY file-upload-app/package*.json ./

RUN npm install

# Bundle app source
COPY file-upload-app/ .

EXPOSE 5001

CMD [ "npm", "start" ]
