name: Print Secrets

on: [push]

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets contents
        run: |
          echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}"
          echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}"
          echo "GOOGLE_SERVICE_ACCOUNT_JSON: ${GOOGLE_SERVICE_ACCOUNT_JSON}"
          echo "SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
