name: Check Secrets

on: [push]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets are set
        run: |
          check_secret() {
            if [ -z "$1" ]; then
              echo "$2 is not set"
            else
              echo "$2 is set and has length ${#1}"
            fi
          }

          check_secret "${AWS_ACCESS_KEY_ID}" "AWS_ACCESS_KEY_ID"
          check_secret "${AWS_SECRET_ACCESS_KEY}" "AWS_SECRET_ACCESS_KEY"
          check_secret "${GOOGLE_SERVICE_ACCOUNT_JSON}" "GOOGLE_SERVICE_ACCOUNT_JSON"
          check_secret "${SSH_PRIVATE_KEY}" "SSH_PRIVATE_KEY"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
