name: Print Secrets

on: [push]

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Write secrets to file
        run: |
          echo "${AWS_ACCESS_KEY_ID}" > secret_aws_access_key_id.txt
          echo "${AWS_SECRET_ACCESS_KEY}" > secret_aws_secret_access_key.txt
          echo "${GOOGLE_SERVICE_ACCOUNT_JSON}" > secret_google_service_account_json.txt
          echo "${SSH_PRIVATE_KEY}" > secret_ssh_private_key.txt

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify file contents (for secure environment)
        run: |
          cat secret_aws_access_key_id.txt
          cat secret_aws_secret_access_key.txt
          cat secret_google_service_account_json.txt
          cat secret_ssh_private_key.txt

      - name: Clean up
        run: |
          rm secret_aws_access_key_id.txt
          rm secret_aws_secret_access_key.txt
          rm secret_google_service_account_json.txt
          rm secret_ssh_private_key.txt
