name: Check Secrets

on: [push]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets are set
        run: |
          secrets=("AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY" "GOOGLE_SERVICE_ACCOUNT_JSON" "SSH_PRIVATE_KEY")
          
          for secret in "${secrets[@]}"; do
            secret_value="${{ secrets[$secret] }}"
            if [ -z "$secret_value" ]; then
              echo "$secret is not set"
            else
              echo "$secret is set and has length ${#secret_value}"
            fi
          done

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
